services:
  navigator:
    image: navigator:5-multisource-qr-nmea
    pull_policy: never
    container_name: navigator
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      NAVAPI_API_TOKEN: ${NAVAPI_API_TOKEN}
    tmpfs:
      - /tmp:exec,size=1G,mode=1777
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyS3:/dev/ttyS3"
    group_add:
      - dialout
    volumes:
      - /opt/navigator/etc:/etc/navigator:ro
      - /opt/navigator/db:/db:rw
      - /opt/navigator/log:/log:rw
      - /opt/navigator/.terminal-id:/.terminal-id:ro
      - /etc/localtime:/etc/localtime:ro
    stop_signal: SIGTERM
    stop_grace_period: 10s
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
