# v.1.0.7 сборка onefile  
# version: "3.9"

services:
  navterminal:
    image: navterminal-msg-irma-sos:v.1.0.8
    build:
        context: .
        dockerfile: docker/Dockerfile
        network: host
    container_name: navterminal 
    restart: always

    tmpfs:
      - /tmp:exec,size=1G,mode=1777

    network_mode: host
    
    # FastAPI
    ports:
        - "7100:7100"
        - "4050:4050"

    # Последовательный порт
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyS3:/dev/ttyS3"

    # Данные, конфиги, логи, sqlite, localtime
    volumes:
      - /home/teamhd/NavTerminal/NDTPClient/etc:/data/NDTPClient/etc
      - /home/teamhd/NavTerminal/NDTPClient/db:/data/NDTPClient/db
      - /home/teamhd/NavTerminal/NDTPClient/log:/data/NDTPClient/log
      - /home/teamhd/NavTerminal/NavAPIServer/etc:/data/NavAPIServer/etc
      - /home/teamhd/NavTerminal/NavAPIServer/db:/data/NavAPIServer/db
      - /home/teamhd/NavTerminal/NavAPIServer/logs:/data/NavAPIServer/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    logging:
        driver: local 
        options:
            max-size: "10m"
            max-file: "5"

    # Если нужны права на serial
    group_add:
      - dialout

    # Чтобы корректно завершались оба процесса
    stop_signal: SIGTERM
    stop_grace_period: 10s
